colors:
  primary:
    background: '#24273a'
    foreground: '#cad3f5'
  normal:
    black   : '#494d64'
    red     : '#ed8796'
    green   : '#a6da95'
    yellow  : '#eed49f'
    blue    : '#8aadf4'
    magenta : '#f5bde6'
    cyan    : '#8bd5ca'
    white   : '#b8c0e0'
  bright:
    black   : '#5b6078'
    red     : '#ed8796'
    green   : '#a6da95'
    yellow  : '#eed49f'
    blue    : '#8aadf4'
    magenta : '#f5bde6'
    cyan    : '#8bd5ca'
    white   : '#a5adcb'

font:
  normal:
    family: JetBrains Mono
    style: Regular
  bold:
    family: JetBrains Mono
    style: Bold
  italic:
    family: JetBrains Mono
    style: Italic
  size: 11.0

