[colors.bright]
black = "#5b6078"
blue = "#8aadf4"
cyan = "#8bd5ca"
green = "#a6da95"
magenta = "#f5bde6"
red = "#ed8796"
white = "#a5adcb"
yellow = "#eed49f"

[colors.normal]
black = "#494d64"
blue = "#8aadf4"
cyan = "#8bd5ca"
green = "#a6da95"
magenta = "#f5bde6"
red = "#ed8796"
white = "#b8c0e0"
yellow = "#eed49f"

[colors.primary]
background = "#24273a"
foreground = "#cad3f5"

[font]
size = 11.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"
